### ISSUE TITLE
AnnotatedTextProvider should handle the case where a TagDefinition cannot be found

### ISSUE THREAD

**Issue by mpetris** [mpetris/catma#225]
`buildAnnotatedKeywordInContext(List<Range> ranges, KwicProvider kwicProvider, TagDefinition tagDefinition, String tagPath)` 
can receive `null` for a `tagDefinition`

**Comment by mpetris** [comment]
java.lang.NullPointerException
        at de.catma.ui.module.annotate.annotationpanel.AnnotatedTextProvider.buildAnnotatedKeywordInContext(AnnotatedTextProvider.java:118)
        at de.catma.ui.module.analyze.visualization.kwic.KwicItemHandler.getKeywordDescription(KwicItemHandler.java:102)
        at de.catma.ui.module.analyze.visualization.kwic.KwicPanel.lambda$initComponents$59302d55$1(KwicPanel.java:449)
        at com.vaadin.ui.Grid$Column$1.generateData(Grid.java:908)

**Comment by maltem-za** [comment]
Not clear why the `tagDefinition` can be null.
